export const DEDUCTION_KEYWORDS = [
  "ADVANCE", "LOAN", "LOC", "LINE OF CREDIT", "OLB", "OCC", "LENDER", "FUNDING", "NEXTGEAR", "CASHFLOW FUNDING",
  "EQUIPMENT FINANCE", "ASSET LEASE", "PERSONAL LOAN", "OVERDRAFT", "OD", "PROVISIONAL CREDIT", "TEMPORARY CREDIT",
  "A2A", "ACCOUNT TO ACCOUNT", "TRANSFER", "FUNDS TRANSFER", "XFR", "XFER", "CBUSOL TRANSFER", "ONLINE TRANSFER",
  "ONLINE XFER", "ONLINE BANKING", "MOBILE BANKING", "TELE TRANSFER", "TELEPHONE TRANSFER", "PC TRANSFER",
  "CASH MANAGEMENT", "MGMNT", "PAYROLL", "CHECKING TRANSFER", "SAVINGS TRANSFER", "MMA TRANSFER", "DEPOSIT TRANSFER",
  "FROM ACCOUNT", "ACCT TRANSFER", "OWNER TRANSFER", "BUSINESS TRANSFER", "ACORNS", "MEMBER CONTRIBUTION",
  "SHAREHOLDER CONTRIBUTION", "PARTNER CONTRIBUTION", "CAPITAL CONTRIBUTION", "OWNER INVESTMENT", "OWNER DEPOSIT",
  "MEMBER DEPOSIT", "PERSONAL TRANSFER", "LOAN PROCEEDS", "CASH ADVANCE", "CREDIT LINE", "OD CREDIT", "LOAN FUNDING",
  "LENDING", "FINANCING", "FUNDED LOAN", "WORKING CAPITAL", "SBA LOAN", "EIDL", "PPP", "KABBAGE", "ONDECK", "BLUEVINE",
  "FUNDING CIRCLE", "PAYPAL WORKING CAPITAL", "ASSET FINANCE", "LEASE FUNDING", "EQUIPMENT LOAN", "REFUND",
  "CUSTOMER REFUND", "MERCHANT REFUND", "REVERSAL", "REVERSAL CREDIT", "CREDIT ADJUSTMENT", "ADJUSTMENT", "CORRECTION",
  "DEPOSIT CORRECTION", "ERROR CORRECTION", "ERROR DEPOSIT", "NSF", "RETURN ITEM", "RETURNED ITEM", "RET", "RTN",
  "ACH RETURN", "PAYMENT RETURN", "RETURN DEPOSIT", "VERIFY", "VERIFICATION", "ACCTVERIFY", "ACCOUNT VERIFY",
  "TRIAL DEPOSIT", "MICRO DEPOSIT", "TEST DEPOSIT", "PRENOTE", "PRE-NOTE", "REWARD", "REWARDS", "CASHBACK", "CASH BACK",
  "REBATE", "RBT", "POINTS REWARD", "CARD REWARD", "INTEREST", "INTEREST PAYMENT", "DIVIDEND", "DIVIDEND CREDIT",
  "SAVINGS INTEREST", "MMA INTEREST", "CD INTEREST", "TREAS", "TREASURY", "IRS TREAS", "US TREASURY", "SSA", "SOC SEC",
  "SOCIAL SECURITY", "VA BENEFIT", "GOV PAYMENT", "STATE REFUND", "TAX REFUND", "FEE REVERSAL", "SERVICE CHARGE REVERSAL",
  "OVERDRAFT REVERSAL", "BANK REFUND", "BANK CREDIT"
];

export const REVENUE_KEYWORDS = [
  "ACH CREDIT", "ACH DEP", "ACH DEPOSIT", "DIRECT DEPOSIT", "PAYMENT RECEIVED", "CUSTOMER PAYMENT", "CLIENT PAYMENT",
  "RECEIVABLE PAYMENT", "INVOICE PAYMENT", "ACH PAYMENT", "EFT CREDIT", "ELECTRONIC CREDIT", "STRIPE", "SHOPIFY PAYMENTS",
  "SHOPIFY PAYOUT", "SQUARE", "BLOCK INC", "CLOVER", "TOAST", "PAYPAL", "PAYPAL TRANSFER", "PAYPAL PAYMENT",
  "VENMO BUSINESS", "ZELLE PAYMENT", "AUTHORIZE.NET", "FIRST DATA", "ELAVON", "WORLDPAY", "CHASE PAYMENTECH", "HEARTLAND",
  "FISERV", "TSYS", "GLOBAL PAYMENTS", "MERCHANT SETTLEMENT", "CARD SETTLEMENT", "BATCH SETTLEMENT", "CREDIT CARD SALES",
  "POS SETTLEMENT", "AMAZON PAYMENTS", "AMAZON SETTLEMENT", "AMAZON SERVICES", "AMAZON MARKETPLACE", "EBAY PAYOUT",
  "ETSY PAYOUT", "WALMART MARKETPLACE", "TIKTOK SHOP", "TEMU SELLER", "WAYFAIR PAYMENTS", "WIRE FROM", "DOMESTIC WIRE CREDIT",
  "INCOMING WIRE", "WIRE PAYMENT", "CUSTOMER WIRE", "CLIENT WIRE", "INTERNATIONAL WIRE", "SWIFT CREDIT", "CASH DEPOSIT",
  "ATM DEPOSIT", "BRANCH DEPOSIT", "COUNTER DEPOSIT", "CURRENCY DEPOSIT", "CASH RECEIPT", "CHECK DEPOSIT", "REMOTE DEPOSIT",
  "RDC DEPOSIT", "CHECK CREDIT", "MOBILE CHECK DEPOSIT", "CHECK RECEIVED", "DEPOSIT ITEM", "BILL.COM", "MELIO",
  "QUICKBOOKS PAYMENT", "INTUIT PAYMENT", "PAYMENT NETWORK", "PAYABLES RECEIVABLES", "DEPOSIT"
];

export const WIRE_DEDUCT_KEYWORDS = [
  "WIRE FROM OWNER", "WIRE FROM MEMBER", "WIRE FROM PARTNER", "WIRE FROM SHAREHOLDER", "WIRE FROM LENDER",
  "WIRE FROM LOAN COMPANY", "WIRE FROM LOC", "WIRE FROM RELATED ENTITY", "WIRE FROM SAME BUSINESS"
];

export type RevenueStatus = "revenue" | "deduction" | "unknown";

export function getRevenueStatus(description: string, amount: number | null): RevenueStatus {
  if (amount === null || amount <= 0) return "unknown";
  
  const desc = description.toUpperCase();

  // Special Wire Rules
  for (const keyword of WIRE_DEDUCT_KEYWORDS) {
    if (desc.includes(keyword)) return "deduction";
  }

  // General Deduction Keywords
  for (const keyword of DEDUCTION_KEYWORDS) {
    if (desc.includes(keyword)) return "deduction";
  }

  // General Revenue Keywords
  for (const keyword of REVENUE_KEYWORDS) {
    if (desc.includes(keyword)) return "revenue";
  }

  // Default -> Revenue
  return "revenue";
}
